#ifndef PROJECT5_DEFINE_H_
#define PROJECT5_DEFINE_H_

#define BORDER 5
#define GAME_FIELD_WIDTH 1050
#define INFO_FIELD_HEIGHT 70
#define GAME_FIELD_HEIGHT 700
#define SCREEN_HEIGHT (GAME_FIELD_HEIGHT + INFO_FIELD_HEIGHT)

#define GAME_OBJ_HEIGHT GAME_FIELD_HEIGHT/10
#define GAME_OBJ_WIDTH GAME_FIELD_WIDTH/15

#define DIGGER_TAG 1
#define HOBBIN_TAG 2
#define NOBBIN_TAG 3
#define EMERALD_TAG 4
#define GOLD_TAG 5

#define RIGHT 1
#define LEFT 0
#define UP 2
#define DOWN 3

#endif  //  PROJECT5_DEFINE_H_
